version: '3.4'

services:
  vueexample:
    image: vueexample
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "10080:80"
      - "10443:443"
    build:
      context: .
      dockerfile: VueExample/Dockerfile
